// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: trading.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradingService_ExecuteInstantTrade_FullMethodName = "/trading.TradingService/ExecuteInstantTrade"
	TradingService_StartAutoTrade_FullMethodName      = "/trading.TradingService/StartAutoTrade"
	TradingService_StopAutoTrade_FullMethodName       = "/trading.TradingService/StopAutoTrade"
	TradingService_GetNodeStatus_FullMethodName       = "/trading.TradingService/GetNodeStatus"
	TradingService_GetTradeStats_FullMethodName       = "/trading.TradingService/GetTradeStats"
	TradingService_GetTradeResults_FullMethodName     = "/trading.TradingService/GetTradeResults"
	TradingService_Heartbeat_FullMethodName           = "/trading.TradingService/Heartbeat"
	TradingService_RegisterNode_FullMethodName        = "/trading.TradingService/RegisterNode"
	TradingService_StatusStream_FullMethodName        = "/trading.TradingService/StatusStream"
	TradingService_StartFlashTrade_FullMethodName     = "/trading.TradingService/StartFlashTrade"
	TradingService_StopFlashTrade_FullMethodName      = "/trading.TradingService/StopFlashTrade"
	TradingService_GetFlashTradeStats_FullMethodName  = "/trading.TradingService/GetFlashTradeStats"
	TradingService_ManageAccount_FullMethodName       = "/trading.TradingService/ManageAccount"
)

// TradingServiceClient is the client API for TradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 交易服务定义
type TradingServiceClient interface {
	// 执行即时交易
	ExecuteInstantTrade(ctx context.Context, in *InstantTradeRequest, opts ...grpc.CallOption) (*InstantTradeResponse, error)
	// 开始自动循环交易
	StartAutoTrade(ctx context.Context, in *AutoTradeRequest, opts ...grpc.CallOption) (*AutoTradeResponse, error)
	// 停止自动循环交易
	StopAutoTrade(ctx context.Context, in *StopTradeRequest, opts ...grpc.CallOption) (*StopTradeResponse, error)
	// 获取节点状态
	GetNodeStatus(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*NodeStatusResponse, error)
	// 获取交易统计
	GetTradeStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// 获取交易结果历史
	GetTradeResults(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error)
	// 心跳检测
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 节点注册（被控端启动时立即注册）
	RegisterNode(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error)
	// 实时状态流（双向流）
	StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusStreamRequest, StatusStreamResponse], error)
	// Flash Trade 相关接口
	// 启动Flash Trade
	StartFlashTrade(ctx context.Context, in *FlashTradeRequest, opts ...grpc.CallOption) (*FlashTradeResponse, error)
	// 停止Flash Trade
	StopFlashTrade(ctx context.Context, in *StopFlashTradeRequest, opts ...grpc.CallOption) (*StopFlashTradeResponse, error)
	// 获取Flash Trade状态
	GetFlashTradeStats(ctx context.Context, in *FlashTradeStatsRequest, opts ...grpc.CallOption) (*FlashTradeStatsResponse, error)
	// 账号管理
	ManageAccount(ctx context.Context, in *AccountManageRequest, opts ...grpc.CallOption) (*AccountManageResponse, error)
}

type tradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingServiceClient(cc grpc.ClientConnInterface) TradingServiceClient {
	return &tradingServiceClient{cc}
}

func (c *tradingServiceClient) ExecuteInstantTrade(ctx context.Context, in *InstantTradeRequest, opts ...grpc.CallOption) (*InstantTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstantTradeResponse)
	err := c.cc.Invoke(ctx, TradingService_ExecuteInstantTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) StartAutoTrade(ctx context.Context, in *AutoTradeRequest, opts ...grpc.CallOption) (*AutoTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoTradeResponse)
	err := c.cc.Invoke(ctx, TradingService_StartAutoTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) StopAutoTrade(ctx context.Context, in *StopTradeRequest, opts ...grpc.CallOption) (*StopTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTradeResponse)
	err := c.cc.Invoke(ctx, TradingService_StopAutoTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) GetNodeStatus(ctx context.Context, in *NodeStatusRequest, opts ...grpc.CallOption) (*NodeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatusResponse)
	err := c.cc.Invoke(ctx, TradingService_GetNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) GetTradeStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, TradingService_GetTradeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) GetTradeResults(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultsResponse)
	err := c.cc.Invoke(ctx, TradingService_GetTradeResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, TradingService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) RegisterNode(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegisterResponse)
	err := c.cc.Invoke(ctx, TradingService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusStreamRequest, StatusStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TradingService_ServiceDesc.Streams[0], TradingService_StatusStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusStreamRequest, StatusStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TradingService_StatusStreamClient = grpc.BidiStreamingClient[StatusStreamRequest, StatusStreamResponse]

func (c *tradingServiceClient) StartFlashTrade(ctx context.Context, in *FlashTradeRequest, opts ...grpc.CallOption) (*FlashTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlashTradeResponse)
	err := c.cc.Invoke(ctx, TradingService_StartFlashTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) StopFlashTrade(ctx context.Context, in *StopFlashTradeRequest, opts ...grpc.CallOption) (*StopFlashTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopFlashTradeResponse)
	err := c.cc.Invoke(ctx, TradingService_StopFlashTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) GetFlashTradeStats(ctx context.Context, in *FlashTradeStatsRequest, opts ...grpc.CallOption) (*FlashTradeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlashTradeStatsResponse)
	err := c.cc.Invoke(ctx, TradingService_GetFlashTradeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ManageAccount(ctx context.Context, in *AccountManageRequest, opts ...grpc.CallOption) (*AccountManageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountManageResponse)
	err := c.cc.Invoke(ctx, TradingService_ManageAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingServiceServer is the server API for TradingService service.
// All implementations must embed UnimplementedTradingServiceServer
// for forward compatibility.
//
// 交易服务定义
type TradingServiceServer interface {
	// 执行即时交易
	ExecuteInstantTrade(context.Context, *InstantTradeRequest) (*InstantTradeResponse, error)
	// 开始自动循环交易
	StartAutoTrade(context.Context, *AutoTradeRequest) (*AutoTradeResponse, error)
	// 停止自动循环交易
	StopAutoTrade(context.Context, *StopTradeRequest) (*StopTradeResponse, error)
	// 获取节点状态
	GetNodeStatus(context.Context, *NodeStatusRequest) (*NodeStatusResponse, error)
	// 获取交易统计
	GetTradeStats(context.Context, *StatsRequest) (*StatsResponse, error)
	// 获取交易结果历史
	GetTradeResults(context.Context, *ResultsRequest) (*ResultsResponse, error)
	// 心跳检测
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 节点注册（被控端启动时立即注册）
	RegisterNode(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error)
	// 实时状态流（双向流）
	StatusStream(grpc.BidiStreamingServer[StatusStreamRequest, StatusStreamResponse]) error
	// Flash Trade 相关接口
	// 启动Flash Trade
	StartFlashTrade(context.Context, *FlashTradeRequest) (*FlashTradeResponse, error)
	// 停止Flash Trade
	StopFlashTrade(context.Context, *StopFlashTradeRequest) (*StopFlashTradeResponse, error)
	// 获取Flash Trade状态
	GetFlashTradeStats(context.Context, *FlashTradeStatsRequest) (*FlashTradeStatsResponse, error)
	// 账号管理
	ManageAccount(context.Context, *AccountManageRequest) (*AccountManageResponse, error)
	mustEmbedUnimplementedTradingServiceServer()
}

// UnimplementedTradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradingServiceServer struct{}

func (UnimplementedTradingServiceServer) ExecuteInstantTrade(context.Context, *InstantTradeRequest) (*InstantTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteInstantTrade not implemented")
}
func (UnimplementedTradingServiceServer) StartAutoTrade(context.Context, *AutoTradeRequest) (*AutoTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAutoTrade not implemented")
}
func (UnimplementedTradingServiceServer) StopAutoTrade(context.Context, *StopTradeRequest) (*StopTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAutoTrade not implemented")
}
func (UnimplementedTradingServiceServer) GetNodeStatus(context.Context, *NodeStatusRequest) (*NodeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedTradingServiceServer) GetTradeStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTradeStats not implemented")
}
func (UnimplementedTradingServiceServer) GetTradeResults(context.Context, *ResultsRequest) (*ResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTradeResults not implemented")
}
func (UnimplementedTradingServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedTradingServiceServer) RegisterNode(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedTradingServiceServer) StatusStream(grpc.BidiStreamingServer[StatusStreamRequest, StatusStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedTradingServiceServer) StartFlashTrade(context.Context, *FlashTradeRequest) (*FlashTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFlashTrade not implemented")
}
func (UnimplementedTradingServiceServer) StopFlashTrade(context.Context, *StopFlashTradeRequest) (*StopFlashTradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopFlashTrade not implemented")
}
func (UnimplementedTradingServiceServer) GetFlashTradeStats(context.Context, *FlashTradeStatsRequest) (*FlashTradeStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlashTradeStats not implemented")
}
func (UnimplementedTradingServiceServer) ManageAccount(context.Context, *AccountManageRequest) (*AccountManageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManageAccount not implemented")
}
func (UnimplementedTradingServiceServer) mustEmbedUnimplementedTradingServiceServer() {}
func (UnimplementedTradingServiceServer) testEmbeddedByValue()                        {}

// UnsafeTradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingServiceServer will
// result in compilation errors.
type UnsafeTradingServiceServer interface {
	mustEmbedUnimplementedTradingServiceServer()
}

func RegisterTradingServiceServer(s grpc.ServiceRegistrar, srv TradingServiceServer) {
	// If the following call pancis, it indicates UnimplementedTradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradingService_ServiceDesc, srv)
}

func _TradingService_ExecuteInstantTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstantTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ExecuteInstantTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ExecuteInstantTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ExecuteInstantTrade(ctx, req.(*InstantTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_StartAutoTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).StartAutoTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_StartAutoTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).StartAutoTrade(ctx, req.(*AutoTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_StopAutoTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).StopAutoTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_StopAutoTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).StopAutoTrade(ctx, req.(*StopTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_GetNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).GetNodeStatus(ctx, req.(*NodeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_GetTradeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).GetTradeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_GetTradeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).GetTradeStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_GetTradeResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).GetTradeResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_GetTradeResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).GetTradeResults(ctx, req.(*ResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).RegisterNode(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TradingServiceServer).StatusStream(&grpc.GenericServerStream[StatusStreamRequest, StatusStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TradingService_StatusStreamServer = grpc.BidiStreamingServer[StatusStreamRequest, StatusStreamResponse]

func _TradingService_StartFlashTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).StartFlashTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_StartFlashTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).StartFlashTrade(ctx, req.(*FlashTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_StopFlashTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopFlashTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).StopFlashTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_StopFlashTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).StopFlashTrade(ctx, req.(*StopFlashTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_GetFlashTradeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashTradeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).GetFlashTradeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_GetFlashTradeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).GetFlashTradeStats(ctx, req.(*FlashTradeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ManageAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountManageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).ManageAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_ManageAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).ManageAccount(ctx, req.(*AccountManageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradingService_ServiceDesc is the grpc.ServiceDesc for TradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trading.TradingService",
	HandlerType: (*TradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteInstantTrade",
			Handler:    _TradingService_ExecuteInstantTrade_Handler,
		},
		{
			MethodName: "StartAutoTrade",
			Handler:    _TradingService_StartAutoTrade_Handler,
		},
		{
			MethodName: "StopAutoTrade",
			Handler:    _TradingService_StopAutoTrade_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _TradingService_GetNodeStatus_Handler,
		},
		{
			MethodName: "GetTradeStats",
			Handler:    _TradingService_GetTradeStats_Handler,
		},
		{
			MethodName: "GetTradeResults",
			Handler:    _TradingService_GetTradeResults_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _TradingService_Heartbeat_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _TradingService_RegisterNode_Handler,
		},
		{
			MethodName: "StartFlashTrade",
			Handler:    _TradingService_StartFlashTrade_Handler,
		},
		{
			MethodName: "StopFlashTrade",
			Handler:    _TradingService_StopFlashTrade_Handler,
		},
		{
			MethodName: "GetFlashTradeStats",
			Handler:    _TradingService_GetFlashTradeStats_Handler,
		},
		{
			MethodName: "ManageAccount",
			Handler:    _TradingService_ManageAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _TradingService_StatusStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "trading.proto",
}
